version: '3'
services:
  web:
    container_name: nodepad-container
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: "mongo"
    volumes:
      - ../mongodb:/data/db
    ports:
      - "27017:27017"
